version: '3.8'
services:
db:
image: mysql:8.0
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: catalog
ports:
- '3306:3306'
command: --default-authentication-plugin=mysql_native_password


api:
build: ./api
depends_on:
- db
ports:
- '3000:3000'

healthcheck:
  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  interval: 10s
  timeout: 5s
  retries: 5

