version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: catalog_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      # keep compatibility envs (some images recognize MYSQL_*)
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./schema-mariadb.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data:/var/lib/mysql-files
    networks:
      - catalog_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: ./api
    container_name: catalog_api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - catalog_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  catalog_network:
    driver: bridge
